"""'new_tab'

Revision ID: 00dca4360902
Revises: 7163f5d87276
Create Date: 2022-04-01 10:07:29.833348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00dca4360902'
down_revision = '7163f5d87276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('navbarbutton', sa.Column('new_tabe', sa.Boolean(), nullable=False))
    op.alter_column('navbarbutton', 'href',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('navbarbutton', 'navbarcat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('navbarbutton', 'new_tab')
    op.add_column('person', sa.Column('telegram_id', sa.String(length=50, collation='NOCASE'), nullable=True))
    op.create_unique_constraint(None, 'person', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'telegram_id')
    op.add_column('navbarbutton', sa.Column('new_tab', sa.VARCHAR(length=25), nullable=True))
    op.alter_column('navbarbutton', 'navbarcat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('navbarbutton', 'href',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('navbarbutton', 'new_tabe')
    # ### end Alembic commands ###
