"""'test12'

Revision ID: 26d17de7c14e
Revises: 3a8d66b30b41
Create Date: 2022-04-03 10:52:21.312527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d17de7c14e'
down_revision = '3a8d66b30b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('type_asset_type',
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], )
    )
    op.add_column('asset', sa.Column('model', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_model', ['model'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    op.drop_column('asset', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('type', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_column('asset', 'model')
    op.drop_table('type_asset_type')
    op.drop_table('asset_model')
    # ### end Alembic commands ###
