"""'test8'

Revision ID: 27ec947650ed
Revises: 3bfe5c65600f
Create Date: 2022-04-01 18:22:57.449942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ec947650ed'
down_revision = '3bfe5c65600f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_aggregaat',
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('aggregaat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aggregaat_id'], ['aggregaat.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], )
    )
    op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_type', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_table('asset_aggregaat')
    # ### end Alembic commands ###
