"""empty message

Revision ID: 38a90d0a1596
Revises: ce00537f05f5
Create Date: 2022-05-12 17:18:49.937644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a90d0a1596'
down_revision = 'ce00537f05f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('FirstRegistration', sa.DateTime(), nullable=True))
    op.add_column('asset', sa.Column('EuroNorm', sa.String(length=10), nullable=True))
    op.add_column('asset', sa.Column('kindWacs', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'asset', ['wacs_id'])
    op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_model', ['model'], ['id'])
    op.drop_column('asset', 'type')
    op.create_foreign_key(None, 'repair_request', 'asset', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'users', 'asset', ['current_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'repair_request', type_='foreignkey')
    op.add_column('asset', sa.Column('type', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='unique')
    op.drop_column('asset', 'kindWacs')
    op.drop_column('asset', 'EuroNorm')
    op.drop_column('asset', 'FirstRegistration')
    # ### end Alembic commands ###
