"""empty message

Revision ID: 3a2a6d139032
Revises: d5b6f2d7ed88
Create Date: 2022-04-01 10:40:29.867358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2a6d139032'
down_revision = 'd5b6f2d7ed88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('navbarbutton', 'navbarcat_id',
               existing_type=sa.INTEGER(),

               nullable=False)
    op.add_column('person', sa.Column('telegram_id', sa.String(length=50, collation='NOCASE'), nullable=True))
    op.create_unique_constraint(None, 'person', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'telegram_id')
    op.alter_column('navbarbutton', 'navbarcat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
