"""'test1'

Revision ID: 496614549be0
Revises: 3a2a6d139032
Create Date: 2022-04-01 10:46:00.188347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496614549be0'
down_revision = '3a2a6d139032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('navbarbutton', 'navbarcat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('person', sa.Column('telegram_id', sa.String(length=50, collation='NOCASE'), nullable=True))
    op.create_unique_constraint(None, 'person', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'telegram_id')
    op.alter_column('navbarbutton', 'navbarcat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
