"""'asset_brand'

Revision ID: 4d0ffc505ba2
Revises: 6b5d5f01d677
Create Date: 2022-04-01 11:56:58.027348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0ffc505ba2'
down_revision = '6b5d5f01d677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_brands', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'asset_brands', 'asset', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_brands', type_='foreignkey')
    op.drop_column('asset_brands', 'asset_id')
    # ### end Alembic commands ###
