"""'test11'

Revision ID: 5255987e3f14
Revises: fb2394cb7d2a
Create Date: 2022-04-02 16:29:05.084963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5255987e3f14'
down_revision = 'fb2394cb7d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'asset', 'asset_type', ['type'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    # ### end Alembic commands ###
