"""'test13'

Revision ID: 5ba345a32038
Revises: 26d17de7c14e
Create Date: 2022-04-03 10:56:24.112147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba345a32038'
down_revision = '26d17de7c14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_model',
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('Asset_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Asset_model_id'], ['asset_model.id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], )
    )
    op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_model', ['model'], ['id'])
    op.drop_column('asset', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('type', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_table('check_model')
    # ### end Alembic commands ###
