"""empty message

Revision ID: 6384fedda70e
Revises: 260e1a8b47aa
Create Date: 2022-05-15 10:03:16.268793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6384fedda70e'
down_revision = '260e1a8b47aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'asset', ['wacs_id'])
    op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_model', ['model'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    op.drop_column('asset', 'type')
    op.add_column('datatable_filters', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'datatable_filters', type_='foreignkey')
    op.create_foreign_key(None, 'datatable_filters', 'users', ['user_id'], ['id'])
    op.drop_column('datatable_filters', 'user')
    op.create_foreign_key(None, 'repair_request', 'asset', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'users', 'asset', ['current_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'repair_request', type_='foreignkey')
    op.add_column('datatable_filters', sa.Column('user', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'datatable_filters', type_='foreignkey')
    op.create_foreign_key(None, 'datatable_filters', 'users', ['user'], ['id'])
    op.drop_column('datatable_filters', 'user_id')
    op.add_column('asset', sa.Column('type', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='unique')
    # ### end Alembic commands ###
