"""'test5'

Revision ID: 6b5d5f01d677
Revises: e8d1175d6389
Create Date: 2022-04-01 11:11:02.964624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5d5f01d677'
down_revision = 'e8d1175d6389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('milles', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'milles')
    # ### end Alembic commands ###
