"""'test8'

Revision ID: 7cfd3b2709f7
Revises: 5ba345a32038
Create Date: 2022-04-03 11:28:56.013095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfd3b2709f7'
down_revision = '5ba345a32038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('wacs_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'asset', ['wacs_id'])
    op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_model', ['model'], ['id'])
    op.drop_column('asset', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('type', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='unique')
    op.drop_column('asset', 'wacs_id')
    # ### end Alembic commands ###
