"""empty message

Revision ID: 94ac2c84d3dc
Revises: 6384fedda70e
Create Date: 2022-05-15 10:05:03.228121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ac2c84d3dc'
down_revision = '6384fedda70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datatable_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.Column('bnName', sa.String(length=50), nullable=True),
    sa.Column('bnValue', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'asset', ['wacs_id'])
    op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_model', ['model'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    op.drop_column('asset', 'type')
    op.create_foreign_key(None, 'repair_request', 'asset', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'users', 'asset', ['current_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'repair_request', type_='foreignkey')
    op.add_column('asset', sa.Column('type', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='unique')
    op.drop_table('datatable_filters')
    # ### end Alembic commands ###
