"""test51

Revision ID: b6a4c92f5550
Revises: 0c7518c5cbca
Create Date: 2022-04-14 11:33:04.478992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a4c92f5550'
down_revision = '0c7518c5cbca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assets',
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # op.create_unique_constraint(None, 'asset', ['wacs_id'])
    # op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    # op.create_foreign_key(None, 'asset', 'asset_model', ['model'], ['id'])
    # op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    # op.drop_column('asset', 'type')
    # op.create_foreign_key(None, 'users', 'asset', ['current_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('asset', sa.Column('type', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='unique')
    op.drop_table('user_assets')
    # ### end Alembic commands ###
