"""'test10'

Revision ID: ba76b9430279
Revises: f64949d92bda
Create Date: 2022-04-02 16:00:35.615183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba76b9430279'
down_revision = 'f64949d92bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('photo', sa.Boolean(), nullable=True))
    op.add_column('checks', sa.Column('photo_sporadic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'photo_sporadic')
    op.drop_column('checks', 'photo')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    # ### end Alembic commands ###
