"""'test11'

Revision ID: ca3171a699d1
Revises: ba76b9430279
Create Date: 2022-04-02 16:10:16.694442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3171a699d1'
down_revision = 'ba76b9430279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_aggregaten',
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('aggregaat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aggregaat_id'], ['aggregaat.id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], )
    )
    op.create_table('check_cat_checks',
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('check_cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_cat_id'], ['check_cat.id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], )
    )
    op.create_table('check_person',
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], )
    )
    op.create_table('check_roles',
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('check_type',
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('Asset_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Asset_type_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], )
    )
    op.create_table('check_assets',
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], )
    )
    op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_type', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_table('check_assets')
    op.drop_table('check_type')
    op.drop_table('check_roles')
    op.drop_table('check_person')
    op.drop_table('check_cat_checks')
    op.drop_table('check_aggregaten')
    # ### end Alembic commands ###
