"""test56

Revision ID: ce00537f05f5
Revises: 124a6f30f7c0
Create Date: 2022-04-17 09:26:27.223128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce00537f05f5'
down_revision = '124a6f30f7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_request', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repair_request', 'asset', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'users', 'asset', ['current_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'repair_request', type_='foreignkey')
    op.drop_column('repair_request', 'asset_id')
    op.add_column('asset', sa.Column('type', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='unique')
    # ### end Alembic commands ###
