"""'new_tab1'

Revision ID: d5b6f2d7ed88
Revises: 6034abee4e39
Create Date: 2022-04-01 10:35:05.755772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b6f2d7ed88'
down_revision = '6034abee4e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('navbarbutton', 'new_tab')
    op.add_column('person', sa.Column('telegram_id', sa.String(length=50, collation='NOCASE'), nullable=True))
    op.create_unique_constraint(None, 'person', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'telegram_id')
    op.add_column('navbarbutton', sa.Column('new_tabe', sa.BOOLEAN(), nullable=True))
    op.alter_column('navbarbutton', 'navbarcat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
