"""'test3'

Revision ID: e8d1175d6389
Revises: 3e04e0f01ac4
Create Date: 2022-04-01 10:50:25.312417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d1175d6389'
down_revision = '3e04e0f01ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'person', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    # ### end Alembic commands ###
