"""'test9'

Revision ID: f64949d92bda
Revises: 292d21ff3927
Create Date: 2022-04-02 15:57:54.531271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64949d92bda'
down_revision = '292d21ff3927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('check_answers_check',
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('check_answers_id', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, 'asset', 'asset_status', ['status'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_brands', ['brand'], ['id'])
    op.create_foreign_key(None, 'asset', 'asset_type', ['type'], ['id'])
    op.add_column('checks', sa.Column('photo', sa.Boolean(), nullable=True))
    op.add_column('checks', sa.Column('photo_sporadic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'photo_sporadic')
    op.drop_column('checks', 'photo')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_table('check_answers_check')
    op.drop_table('check_cat')
    # ### end Alembic commands ###
